{% set name = "pymca-zocalo" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 27100359d8a3e3c6ec8d0bc582116deaccb1ffe467388976284c603b94a04488

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pymca
    - python >={{ python_min }}
    - setuptools
    - workflows >=1.7
    - zocalo
    - xraylib

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymca_zocalo

about:
  home: "https://github.com/DiamondLightSource/python-zocalo-pymca"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "PyMca components for automated data processing with Zocalo at Diamond Light Source"

extra:
  recipe-maintainers:
    - rjgildea
    - tschoonj
